;;; lele/elpa.el --- Lele's ELPA specialization

(push 'async esk/packages)
(push 'dockerfile-mode esk/packages)
(push 'elfeed esk/packages)
(push 'elfeed-goodies esk/packages)
(push 'erc-hl-nicks esk/packages)
(push 'google-translate esk/packages)
(push 'nginx-mode esk/packages)
(push 'notmuch esk/packages)
(push 'notmuch-labeler esk/packages)
(push 'rainbow-mode esk/packages)
(push 's esk/packages)
(push 'treemacs esk/packages)
(push 'w3m esk/packages)
